version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dammminvitation-app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/.env
      - dammm-storage:/var/www/html/storage/app
      - dammm-logs:/var/www/html/storage/logs
    environment:
      - APP_NAME=Dammminvitation
      - APP_ENV=production
      - APP_KEY=base64:Q0KP94HeBsqK1YXQLjyVXxxun8U00Gw50jrTduiBo84=
      - APP_DEBUG=false
      - APP_URL=https://dammminvitation.ffatahilah.my.id
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=invitaion
      - DB_USERNAME=ffatahilah
      - DB_PASSWORD=OmbaInam#121221
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - FILESYSTEM_DISK=local
      - NGUNDANG_PLATFORM_DOMAIN=dammminvitation.ffatahilah.my.id
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dammm.rule=Host(`dammminvitation.ffatahilah.my.id`)"
      - "traefik.http.routers.dammm.entrypoints=websecure"
      - "traefik.http.routers.dammm.tls=true"
      - "traefik.http.routers.dammm.tls.certresolver=letsencrypt"
      - "traefik.http.services.dammm.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  dammm-storage:
    driver: local
  dammm-logs:
    driver: local
